[package]
name = "apedb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc-any = "2.4.2"
uuid = {version = "0.8.2", features = ["v4"]}
simple-error = "0.2.3"
